version: '3.8'

services:
  nicknameservice:
    build:
      context: ./nicknameservice
      dockerfile: Dockerfile
    container_name: nicknameservice
    restart: always

  hackernickname:
    build:
      context: ./HackerNickName
      dockerfile: Dockerfile
    container_name: HackerNickName
    ports:
      - "8090:8090"
    depends_on:
      - nicknameservice
    restart: always
